# azure-pipelines.yml
trigger: none

parameters:
  - name: "DESCRIPTION"
    type: string
    default: "Load test"
  - name: "rate"
    displayName: "rate"
    type: string
    default: "10"
  - name: "duration"
    displayName: "duration"
    type: string
  - name: "rampingDuration"
    displayName: "rampingDuration"
    type: string
  - name: "preAllocatedVUs"
    displayName: "preAllocatedVUs"
    type: string
    default: "10"
  - name: "maxVUs"
    displayName: "maxVUs"
    type: string
    default: "10"
  - name: "TEST_MAIL_FROM"
    displayName: "TEST_MAIL_FROM"
    type: string
  - name: "TEST_MAIL_TO"
    displayName: "TEST_MAIL_TO"
    type: string
  - name: "NOTICE_CODE_PREFIX"
    displayName: "NOTICE_CODE_PREFIX"
    type: string
  - name: "URL_BASE_PATH"
    displayName: "URL_BASE_PATH"
    type: string
    values:
      - "https://api.uat.platform.pagopa.it/ecommerce/payment-methods-service/v1"
      - "https://api.uat.platform.pagopa.it/ecommerce/payment-requests-service/v1"
      - "https://api.uat.platform.pagopa.it/ecommerce/transactions-service/v1"
      - "https://api.uat.platform.pagopa.it/ecommerce/notifications-service/v1"
      - "https://api.uat.platform.pagopa.it/ecommerce/checkout/v1"
      - "https://api.dev.platform.pagopa.it/ecommerce/checkout/v1"
      - "https://api.uat.platform.pagopa.it"
  - name: "PAYMENT_METHOD_NAME"
    displayName: "PAYMENT_METHOD_NAME"
    type: string
  - name: "SCRIPT"
    displayName: "Script name"
    type: string
    values:
      - soak-test-notifications
      - soak-test-carts
      - soak-test-verification
      - soak-test-payment-methods
      - soak-test-transaction-activation
      - soak-test-transaction-auth
      - perf-test-payment-methods
      - perf-test-psps-by-payment-methods
  # optional sub path where the project to be initialized is located. To be used on repository with multiple projects.
  - name: "projectDir"
    type: string
    default: "." # current folder is default
  # if not set, the Node version will be red from .node-version and -nvmrc files, in this order
  - name: "nodeVersion"
    type: string
    default: "none"
  - name: "BYPASS_APIM"
    displayName: "BYPASS_APIM"
    type: boolean
    default: False
    values:
      - False
      - True

stages : 
  - stage : 'run_with_APIM'
    displayName: 'Run with APIM'
    condition: eq(${{parameters.BYPASS_APIM}}, false)
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: performance_test_with_APIM
        steps:
          - template: azure-templates/soaktest-template.yaml
            parameters:
              URL_BASE_PATH: ${{ parameters['URL_BASE_PATH'] }} 
              TEST_MAIL_FROM: ${{ parameters['TEST_MAIL_FROM'] }} 
              TEST_MAIL_TO: ${{ parameters['TEST_MAIL_TO'] }} 
              PAYMENT_METHOD_NAME: ${{ parameters['PAYMENT_METHOD_NAME'] }}
              rate: ${{ parameters['rate'] }} 
              duration: ${{ parameters['duration'] }} 
              preAllocatedVUs: ${{ parameters['preAllocatedVUs'] }}
              maxVUs: ${{ parameters['maxVUs'] }} 
              projectDir: ${{ parameters['projectDir']}}
              nodeVersion: ${{ parameters['nodeVersion']}}
              SCRIPT: ${{ parameters['SCRIPT']}}
              DESCRIPTION: ${{ parameters['DESCRIPTION']}}
              NOTICE_CODE_PREFIX: ${{ parameters['NOTICE_CODE_PREFIX']}}
              rampingDuration: ${{ parameters['rampingDuration']}}
              
  - stage : 'run_without_APIM'
    displayName: 'Run without APIM'
    condition: eq(${{parameters.BYPASS_APIM}}, true)
    pool:
      name: pagopa-uat-linux
    jobs:
      - job: performance_test_without_APIM
        steps :
          - template: azure-templates/soaktest-template.yaml
            parameters:
              URL_BASE_PATH: ${{ parameters['URL_BASE_PATH'] }}
              TEST_MAIL_FROM: ${{ parameters['TEST_MAIL_FROM'] }} 
              TEST_MAIL_TO: ${{ parameters['TEST_MAIL_TO'] }} 
              PAYMENT_METHOD_NAME: ${{ parameters['PAYMENT_METHOD_NAME'] }}
              rate: ${{ parameters['rate'] }} 
              duration: ${{ parameters['duration'] }} 
              preAllocatedVUs: ${{ parameters['preAllocatedVUs'] }}
              maxVUs: ${{ parameters['maxVUs'] }}
              projectDir: ${{ parameters['projectDir']}}
              nodeVersion: ${{ parameters['nodeVersion']}}
              SCRIPT: ${{ parameters['SCRIPT']}}
              DESCRIPTION: ${{ parameters['DESCRIPTION']}}
              NOTICE_CODE_PREFIX: ${{ parameters['NOTICE_CODE_PREFIX']}}
              rampingDuration: ${{ parameters['rampingDuration']}}
